title: Chat Playground Lab Book
description: A comprehensive, hands-on learning resource for LLM/Gen AI security concepts
author: Steve
baseurl: "/chat-playground-lab-book"
url: "https://virtualsteve-star.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - PROJECT_README.md
  - "Chat Playground Lab Book.md" 