title: Chat Playground Lab Book
description: A comprehensive, hands-on learning resource for LLM/Gen AI security concepts
author: Steve
email: your-email@example.com
baseurl: "/chat-playground-lab-book"
url: "https://virtualsteve-star.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  labs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "labs"
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-relative-links

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 